### ISSUE TITLE
Error in response to sockets.tcp.getInfo: TypeError: this.isPaused is not a function

### ISSUE THREAD

**Issue by stevenmason** [feross/chrome-net#30]
When connecting to a server I get this error on this line: 

`if (!this.isPaused()) this.read(0)`

the code:
		
```
        var server = net.createServer()
		
		server.on('listening', function () {
			console.log('listening');
		});
		
		server.on('connection', function (socket) { 
			console.log('connection:' + socket);
		});
		
		server.listen(8080);
```

**Comment by feross** [comment]
`isPaused` is a method that is available in node streams3. If you're missing that, then try updating the version of browserify that you are using. The latest version is currently 13.
